(define (problem extension1) (:domain extension1)
(:objects
 book0 book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12 book13 book14 book15 book16 book17 book18 book19 - libro
 enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre - mes
)
(:init 
;Juego de Prueba meses
    (= (mesANumero enero) 1)
    (= (mesANumero febrero) 2)
    (= (mesANumero marzo) 3)
    (= (mesANumero abril) 4)
    (= (mesANumero mayo) 5)
    (= (mesANumero junio) 6)
    (= (mesANumero julio) 7)
    (= (mesANumero agosto) 8)
    (= (mesANumero septiembre) 9)
    (= (mesANumero octubre) 10)
    (= (mesANumero noviembre) 11)
    (= (mesANumero diciembre) 12)
;Juego de Prueba de mes libro Planificado
    (= (mesLibroPlanificado book0) 0)
    (= (mesLibroPlanificado book1) 0)
    (= (mesLibroPlanificado book2) 0)
    (= (mesLibroPlanificado book3) 0)
    (= (mesLibroPlanificado book4) 0)
    (= (mesLibroPlanificado book5) 0)
    (= (mesLibroPlanificado book6) 0)
    (= (mesLibroPlanificado book7) 0)
    (= (mesLibroPlanificado book8) 0)
    (= (mesLibroPlanificado book9) 0)
    (= (mesLibroPlanificado book10) 0)
    (= (mesLibroPlanificado book11) 0)
    (= (mesLibroPlanificado book12) 0)
    (= (mesLibroPlanificado book13) 0)
    (= (mesLibroPlanificado book14) 0)
    (= (mesLibroPlanificado book15) 0)
    (= (mesLibroPlanificado book16) 0)
    (= (mesLibroPlanificado book17) 0)
    (= (mesLibroPlanificado book18) 0)
    (= (mesLibroPlanificado book19) 0)
;Juego de Prueba de Predecesores
   (esPredecesor book1 book5)
   (esPredecesor book4 book9)
   (esPredecesor book13 book9)
   (esPredecesor book8 book9)
   (esPredecesor book14 book14)
   (esPredecesor book17 book14)
   (esPredecesor book16 book16)
   (esPredecesor book19 book16)
;Juego de Prueba de Leidos
   (libroLeido book13)
   (libroLeido book4)
   (libroLeido book6)
   (libroLeido book14)
   (libroLeido book17)
   (libroLeido book11)
   (libroLeido book15)
   (libroLeido book7)
   (libroLeido book8)
   (libroLeido book18)
   (libroLeido book19)
   (libroLeido book16)
   (libroLeido book9)
   (libroLeido book2)
   (libroLeido book0)
   (libroLeido book12)
   (libroLeido book1)
;Juego de Prueba de Aplanificar
   (libroAPlanificar book3)
   (libroAPlanificar book10)
)
(:goal (not (exists (?l - libro) 
                (and (libroAPlanificar ?l) (not (libroPlanificado ?l)))
              )
          )
    )
)