(define (problem extension1) (:domain extension1)
(:objects 
  book book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12 - libro
  enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre - mes
)
(:init
  (mesAnterior enero febrero)
  (mesAnterior febrero marzo)
  (mesAnterior marzo abril)
  (mesAnterior abril mayo)
  (mesAnterior mayo junio)
  (mesAnterior junio julio)
  (mesAnterior julio agosto)
  (mesAnterior agosto septiembre)
  (mesAnterior septiembre octubre)
  (mesAnterior octubre noviembre)
  (mesAnterior noviembre diciembre)
  
  (mesAnterior enero febrero)
  (mesAnterior enero marzo)
  (mesAnterior enero abril)
  (mesAnterior enero mayo)
  (mesAnterior enero junio)
  (mesAnterior enero julio)
  (mesAnterior enero agosto)
  (mesAnterior enero septiembre)
  (mesAnterior enero octubre)
  (mesAnterior enero noviembre)
  (mesAnterior enero diciembre)

  (mesAnterior febrero marzo)
  (mesAnterior febrero abril)
  (mesAnterior febrero mayo)
  (mesAnterior febrero junio)
  (mesAnterior febrero julio)
  (mesAnterior febrero agosto)
  (mesAnterior febrero septiembre)
  (mesAnterior febrero octubre)
  (mesAnterior febrero noviembre)
  (mesAnterior febrero diciembre)

  (mesAnterior marzo abril)
  (mesAnterior marzo mayo)
  (mesAnterior marzo junio)
  (mesAnterior marzo julio)
  (mesAnterior marzo agosto)
  (mesAnterior marzo septiembre)
  (mesAnterior marzo octubre)
  (mesAnterior marzo noviembre)
  (mesAnterior marzo diciembre)

  (mesAnterior abril mayo)
  (mesAnterior abril junio)
  (mesAnterior abril julio)
  (mesAnterior abril agosto)
  (mesAnterior abril septiembre)
  (mesAnterior abril octubre)
  (mesAnterior abril noviembre)
  (mesAnterior abril diciembre)

  (mesAnterior mayo junio)
  (mesAnterior mayo julio)
  (mesAnterior mayo agosto)
  (mesAnterior mayo septiembre)
  (mesAnterior mayo octubre)
  (mesAnterior mayo noviembre)
  (mesAnterior mayo diciembre)

  (mesAnterior junio julio)
  (mesAnterior junio agosto)
  (mesAnterior junio septiembre)
  (mesAnterior junio octubre)
  (mesAnterior junio noviembre)
  (mesAnterior junio diciembre)

  (mesAnterior julio agosto)
  (mesAnterior julio septiembre)
  (mesAnterior julio octubre)
  (mesAnterior julio noviembre)
  (mesAnterior julio diciembre)

  (mesAnterior agosto septiembre)
  (mesAnterior agosto octubre)
  (mesAnterior agosto noviembre)
  (mesAnterior agosto diciembre)

  (mesAnterior septiembre octubre)
  (mesAnterior septiembre noviembre)
  (mesAnterior septiembre diciembre)

  (mesAnterior octubre noviembre)
  (mesAnterior octubre diciembre)

  (mesAnterior noviembre diciembre)

    ;   ; ;;;;;;;;;;;;;;;;;;Juego de prueba simple
    ; (esPredecesor book book1)
    ; (esPredecesor book1 book2)
    ; (esPredecesor book2 book3)
    ; (esPredecesor book3 book4)
    ; (esPredecesor book4 book5)
    ; (esPredecesor book5 book6)
    ; (esPredecesor book6 book7)
    ; (libroAPlanificar book7)

    ; ;;;;;;;;;;;;;;;;;;Juego de prueba con un predecesores con predecesores, CORREGIDO EL ERROR
    (esPredecesor book2 book3)
    (esPredecesor book3 book6)
    (esPredecesor book3 book5)
    (esPredecesor book4 book5)
    (esPredecesor book5 book6)
    (libroAPlanificar book6)

    ; ;;;;;;;;;;;;;;;;;;Juego de prueba con un dos predecesores con predecesores
    ; (esPredecesor book1 book2)
    ; (esPredecesor book1 book3)
    ; (esPredecesor book2 book4)
    ; (esPredecesor book3 book4)
    ; (libroAPlanificar book4)

    ; ;;;;;;;;;;;;;;;;;;Juego de prueba 4
    ; (esPredecesor book1 book2)
    ; (esPredecesor book1 book3)
    ; (esPredecesor book2 book4)
    ; (esPredecesor book3 book2)
    ; (esPredecesor book3 book4)
    ; (libroAPlanificar book4)


    ; ;;;;;;;;;;;;;;;;;;Juego de prueba 5
    ; (esPredecesor book5 book1)
    ; (esPredecesor book5 book2)
    ; (esPredecesor book5 book3)
    ; (esPredecesor book5 book4)
    ; (esPredecesor book1 book2)
    ; (esPredecesor book2 book3)
    ; (esPredecesor book2 book4)
    ; (esPredecesor book3 book4)
    ; (esPredecesor book3 book7)
    ; (esPredecesor book7 book8)
    ; (esPredecesor book8 book4)
    ; (libroAPlanificar book4)

    ;;;;;;;;;;;;;;;;;;Juego de prueba 6
    ; (esPredecesor book1 book3)
    ; (esPredecesor book3 book4)
    ; (esPredecesor book4 book6)
    ; (esPredecesor book6 book9)
    ; (esPredecesor book9 book11)
    ; (esPredecesor book3 book5)
    ; (esPredecesor book5 book7)
    ; (esPredecesor book5 book8)
    ; (esPredecesor book7 book10)
    ; (esPredecesor book8 book10)
    ; (esPredecesor book10 book11)
    ; (esPredecesor book11 book12)
    ; (libroAPlanificar book12)

)

  (:goal (not (exists (?l - libro) 
                (and (libroAPlanificar ?l) (not (libroPlanificado ?l)))
              )
          )
    )

)